import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "MixWithStazz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body
        className={`antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
